version: "3"
services:
  web:
    build: .
    ports:
      # local:container
      - "8080:8080"
#     db:
#       image: "mysql"
#       environment:
#         MYSQL_ROOT_PASSWORD: "root"
#       volumes:
#         - db-data:/foo
# volumes:
#   db-data:
